version: "3"
services:
  web:
    build: .
    volumes:
      - .:/rails_hello
      - bundle:/usr/local/bundle
    command: ash -c "rm -f /tmp/pids/server.pid && rails s -b '0.0.0.0'"
    ports:
      - 3000:3000
    links:
      - db

  db:
    image: mysql:8.0.16
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password

volumes:
  bundle:
